# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['none', '3.10.0-alpha.6', '3.10.0-alpha.5', '3.10.0-alpha.4', '3.10.0-alpha.3', '3.10.0-alpha.2', '3.10.0-alpha.1', '3.9.2', '3.9.2-rc.1', '3.9.1', '3.9.1-rc.1', '3.9.0', '3.9.0-rc.2', '3.9.0-rc.1', '3.9.0-beta.5', '3.9.0-beta.4', '3.8.8', '3.8.7', '3.8.6', '3.8.5', '3.8.4', '3.8.3', '3.8.2', '3.8.1', '3.8.0', '3.7.10', '3.7.9', '3.7.8', '3.7.7', '3.7.6', '3.7.5', '3.7.1', '3.6.13', '3.6.12', '3.6.11', '3.6.10', '3.6.9', '3.6.8', '3.6.7', '3.5.10', '3.5.9', '3.5.4', '2.7.18', '2.7.17']
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo Python
        which -a python
        echo \nPython 2
        which -a python2
        echo \nPython 3
        which -a python3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      if: matrix.python-version != 'none'
    - run: |
        echo Python
        which -a python
        echo \nPython 2
        which -a python2
        echo \nPython 3
        which -a python3
      if: matrix.python-version != 'none'
    - name: Print info (Python)
      run: |
        python -VV
        python test.py
    - name: Print info (Python 2)
      run: |
        python2 -VV
        python2 test.py
      # if: startsWith(matrix.python-version, '2')
    - name: Print info (Python 3)
      run: |
        python3 -VV
        python3 test.py
      # if: startsWith(matrix.python-version, '3')
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['none', '3.10.0-alpha.6', '3.10.0-alpha.5', '3.10.0-alpha.4', '3.10.0-alpha.3', '3.10.0-alpha.2', '3.10.0-alpha.1', '3.9.2', '3.9.2-rc.1', '3.9.1', '3.9.1-rc.1', '3.9.0', '3.9.0-rc.2', '3.9.0-rc.1', '3.9.0-beta.5', '3.9.0-beta.4', '3.8.8', '3.8.7', '3.8.6', '3.8.5', '3.8.4', '3.8.3', '3.8.2', '3.8.1', '3.8.0', '3.7.9', '3.7.8', '3.7.7', '3.7.6', '3.7.5', '3.7.1', '3.6.8', '3.6.7', '3.5.4', '3.4.4', '3.3.5', '3.2.5', '3.1.4', '3.0.1', '2.7.18', '2.7.17']
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo Python
        which -a python
        echo \nPython 2
        which -a python2
        echo \nPython 3
        which -a python3
    - run: where python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      if: matrix.python-version != 'none'
    - run: |
        echo Python
        which -a python
        echo \nPython 2
        which -a python2
        echo \nPython 3
        which -a python3
      if: matrix.python-version != 'none'
    - name: Print info (Python)
      run: |
        python -VV
        python test.py
    - name: Print info (Python 2)
      run: |
        python2 -VV
        python2 test.py
      # if: startsWith(matrix.python-version, '2')
    - name: Print info (Python 3)
      run: |
        python3 -VV
        python3 test.py
      # if: startsWith(matrix.python-version, '3')
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['none', '3.10.0-alpha.6', '3.10.0-alpha.5', '3.10.0-alpha.4', '3.10.0-alpha.3', '3.10.0-alpha.2', '3.10.0-alpha.1', '3.9.2', '3.9.2-rc.1', '3.9.1', '3.9.1-rc.1', '3.9.0', '3.9.0-rc.2', '3.9.0-rc.1', '3.9.0-beta.5', '3.9.0-beta.4', '3.8.8', '3.8.7', '3.8.6', '3.8.5', '3.8.4', '3.8.3', '3.8.2', '3.8.1', '3.8.0', '3.7.10', '3.7.9', '3.7.8', '3.7.7', '3.7.6', '3.7.5', '3.7.1', '3.6.13', '3.6.12', '3.6.11', '3.6.10', '3.6.9', '3.6.8', '3.6.7', '3.5.10', '3.5.9', '3.5.4', '2.7.18', '2.7.17']
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo Python
        which -a python
        echo \nPython 2
        which -a python2
        echo \nPython 3
        which -a python3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      if: matrix.python-version != 'none'
    - run: |
        echo Python
        which -a python
        echo \nPython 2
        which -a python2
        echo \nPython 3
        which -a python3
      if: matrix.python-version != 'none'
    - name: Print info (Python)
      run: |
        python -VV
        python test.py
    - name: Print info (Python 2)
      run: |
        python2 -VV
        python2 test.py
      # if: startsWith(matrix.python-version, '2')
    - name: Print info (Python 3)
      run: |
        python3 -VV
        python3 test.py
      # if: startsWith(matrix.python-version, '3')
        
